/**
 * POST /api/sync — the thin, boring server (sync spec §5).
 *   1. Authenticate.
 *   2. For each mutation: Zod-validate the envelope + payload, drop anything not
 *      authored by the caller (defense in depth; RLS also enforces), then dispatch
 *      to `sync_<type>`. Validation/RPC failures leave the mutation in the outbox.
 *   3. Pull `mutation_logs` newer than each per-entity cursor (RLS scopes reads).
 * Push-before-pull in one round-trip; the client filters its own acks out of the pull.
 */
import { decodeHLC } from "$lib/sync/hlc";
import { parseMutation, rpcNameFor } from "$lib/sync/mutations";
import type { Database } from "$lib/utils/models/database";
import { type RequestHandler, json } from "@sveltejs/kit";

/** The `sync_*` RPCs all share one arg signature, so any name in the union types the call. */
type SyncRpc = keyof Database["public"]["Functions"] & `sync_${string}`;

interface SyncRequest {
  mutations: unknown[];
  cursors: Record<string, number>;
}

export const POST: RequestHandler = async ({ locals, platform, request }) => {
  const startedAt = Date.now();
  const { supabase, safeGetSession } = locals;
  const { user } = await safeGetSession();
  if (!user) {
    return json({ error: "Unauthorized" }, { status: 401 });
  }

  // Per-user rate limit (auth spec §3.4) to blunt mutation spam. The binding only
  // exists on the deployed Worker; local dev has none, so this is a no-op there.
  const limiter = platform?.env?.SYNC_RATE_LIMITER;
  if (limiter) {
    const { success } = await limiter.limit({ key: user.id });
    if (!success) {
      return json({ error: "Too Many Requests" }, { status: 429 });
    }
  }

  const body = (await request.json()) as SyncRequest;
  const mutations = Array.isArray(body.mutations) ? body.mutations : [];
  const cursors = body.cursors ?? {};

  const processedIds: string[] = [];
  // Permanently unacceptable mutations (malformed envelope, or authored by someone
  // other than the caller). Retrying these can never succeed, so we report them so
  // the client drops them from its outbox instead of retrying forever. Contrast with
  // a transient RPC error below, which stays in the outbox to retry.
  const rejectedIds: string[] = [];
  for (const raw of mutations) {
    let mutation;
    try {
      mutation = parseMutation(raw);
    } catch (err) {
      console.error("[sync] rejected malformed mutation:", err);
      // The envelope failed validation but its `id` is usually still a valid uuid
      // (e.g. only entity_id was malformed) — report it so the client can drop it.
      const id = (raw as { id?: unknown } | null)?.id;
      if (typeof id === "string") rejectedIds.push(id);
      continue;
    }
    // SNAPSHOT is server-generated by compaction, never submitted by clients.
    if (mutation.type === "SNAPSHOT") continue;
    // The author must be the caller; RLS enforces this again at the row level. A
    // mismatch is permanent for this caller, so reject (the client already filters
    // its own push by author, so this is defense in depth).
    if (mutation.user_id !== user.id) {
      rejectedIds.push(mutation.id);
      continue;
    }

    // Causal time for the log row is derived from the HLC's wall component,
    // not the request wall-clock, so it stays consistent with ordering.
    const created_at = new Date(decodeHLC(mutation.hlc).wall).toISOString();

    const { error } = await supabase.rpc(rpcNameFor(mutation.type) as SyncRpc, {
      p_mutation_id: mutation.id,
      p_user_id: user.id,
      p_hlc: mutation.hlc,
      p_created_at: created_at,
      p_entity_id: mutation.entity_id,
      p_payload: mutation.payload,
    });
    if (error) {
      console.error(`[sync] sync_${mutation.type.toLowerCase()} failed:`, error.message);
      continue; // leave it in the outbox to retry
    }
    processedIds.push(mutation.id);
  }

  // Pull each requested entity's tail. RLS scopes rows to what the user may read.
  const newMutations: unknown[] = [];
  const outCursors: Record<string, number> = {};
  for (const [entityId, sinceSeq] of Object.entries(cursors)) {
    const { data, error } = await supabase
      .from("mutation_logs")
      .select("id, type, entity_id, user_id, hlc, payload, seq_id, created_at")
      .eq("entity_id", entityId)
      .gt("seq_id", sinceSeq)
      .order("seq_id", { ascending: true });
    if (error) {
      console.error(`[sync] pull for ${entityId} failed:`, error.message);
      continue;
    }
    const rows = data ?? [];
    newMutations.push(...rows);
    outCursors[entityId] = rows.length > 0 ? rows[rows.length - 1].seq_id : sinceSeq;
  }

  // Structured summary for observability (Cloudflare Workers logs/traces). One line
  // per request: how many mutations were submitted vs accepted, how many pulled,
  // entity fan-out, and latency — enough to spot rejection spikes and slow rounds.
  console.log(
    JSON.stringify({
      evt: "sync",
      user: user.id,
      submitted: mutations.length,
      accepted: processedIds.length,
      // Permanently rejected (dropped by the client). Distinct from a mutation left
      // in the outbox to retry after a transient RPC/network failure.
      rejected: rejectedIds.length,
      retrying: mutations.length - processedIds.length - rejectedIds.length,
      pulled: newMutations.length,
      entities: Object.keys(cursors).length,
      ms: Date.now() - startedAt,
    }),
  );

  return json({ processedIds, rejectedIds, newMutations, cursors: outCursors });
};
