import { getLocaleStrings } from "$lib/utils/common/locale";
import { redirect } from "@sveltejs/kit";

export async function load({ cookies, locals, params, request, url }) {
  const { safeGetSession } = locals;
  const { session, user } = await safeGetSession();

  if (!session || !user) {
    cookies.set("authRedirect", url.pathname, { path: "/", maxAge: 60 * 5 }); // 5 minutes
    redirect(307, "/auth");
  }

  const { strings } = getLocaleStrings(cookies, request, [
    "addPerson",
    "addItem",
    "anonymous",
    "account",
    "logOut",
    "anyoneOnTheInternetCanAccessThisCheque",
    "appName",
    "balance",
    "balanceCalculation{subtrahend}{minuend}",
    "buyer",
    "whichPersonAreYou",
    "claimHint",
    "imNotListed",
    "thisIsMe",
    "thisIsYou",
    "changeWhichPersonIsYou",
    "linkedToYou",
    "cheque",
    "cheque{date}",
    "chequeName",
    "close",
    "person{index}",
    "cost",
    "customize",
    "customSplit",
    "splitEvenly",
    "settleUp",
    "{count}Recipients",
    "{count}Recipient",
    "{payer}Pays{payee}",
    "deleteCheque",
    "downloadCsv",
    "etransfer",
    "exportChequeDataToUseInOtherApplications",
    "home",
    "invited",
    "inviteLink",
    "item",
    "{item}Buyer",
    "{item}ContributionFrom{person}",
    "{item}Cost",
    "item{index}",
    "leaveCheque",
    "linkPaymentAccountTo{payee}",
    "notLinked",
    "onlyInvitedUsersCanAccessThisCheque",
    "owing",
    "owingCalculation{multiplicand}{numerator}{denominator}",
    "owner",
    "paid",
    "{payer}Sends{payee}{value}",
    "paymentId",
    "paymentMethod",
    "payPal",
    "private",
    "public",
    "regenerateInviteLink",
    "remove{item}",
    "settings",
    "share",
    "signInWithGoogle",
    "offline",
    "subtotal",
    "syncError",
    "synced",
    "syncing",
    "theCurrentInvitationLinkWillNoLongerWork",
    "thisWillDeleteTheChequeForAllUsers",
    "total",
    "unlinkYourAccountFrom{payee}",
    "unsyncedChanges",
    "{user}(you)",
    "{user}HasNoPaymentAccountSetUp",
    "users",
    "{value}UnaccountedFor",
    "youWillNotBeAbleToAccessThisChequeAnymore",
  ]);

  return {
    chequeId: params.chequeId,
    origin: url.origin,
    strings,
  };
}
